"""initial schema

Revision ID: 86fca398f8c5
Revises: 
Create Date: 2026-07-28 15:43:10.475072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86fca398f8c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faq',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=100), nullable=False),
    sa.Column('question', sa.String(length=200), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_faq'))
    )
    op.create_table('imgs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img_name', sa.String(length=100), nullable=False),
    sa.Column('img_url', sa.String(length=300), nullable=False),
    sa.Column('img_type', sa.String(length=20), nullable=False),
    sa.Column('event_img', sa.String(length=300), nullable=True),
    sa.Column('is_main', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_imgs'))
    )
    op.create_table('movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('poster_path', sa.String(length=300), nullable=True),
    sa.Column('release_date', sa.String(length=20), nullable=True),
    sa.Column('vote_average', sa.Float(), nullable=True),
    sa.Column('certification', sa.String(length=10), nullable=True),
    sa.Column('genres', sa.String(length=200), nullable=True),
    sa.Column('actors', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_movie')),
    sa.UniqueConstraint('tmdb_id', name=op.f('uq_movie_tmdb_id'))
    )
    op.create_table('notice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('theater', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notice'))
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Productname', sa.String(length=200), nullable=False),
    sa.Column('Producttype', sa.String(length=50), nullable=False),
    sa.Column('Productprice', sa.Integer(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('Productdescription', sa.Text(), nullable=True),
    sa.Column('Productimage_url', sa.String(length=300), nullable=True),
    sa.Column('Productlimit', sa.Integer(), nullable=False),
    sa.Column('Productdate', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product'))
    )
    op.create_table('region',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_region')),
    sa.UniqueConstraint('name', name=op.f('uq_region_name'))
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.String(length=200), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('birth', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('Terms_of_Service', sa.Boolean(), nullable=False),
    sa.Column('Privacy_Policy', sa.Boolean(), nullable=False),
    sa.Column('receive_emails', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='normal', nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('admin_role', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('email', name=op.f('uq_user_email')),
    sa.UniqueConstraint('userid', name=op.f('uq_user_userid'))
    )
    op.create_table('answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notice_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('modify_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['notice_id'], ['notice.id'], name=op.f('fk_answer_notice_id_notice'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_answer_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_answer'))
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('user_userid', sa.String(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('total_price', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('order_code', sa.String(length=100), nullable=True),
    sa.Column('seats_json', sa.Text(), nullable=True),
    sa.Column('people_json', sa.Text(), nullable=True),
    sa.Column('schedule_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_order_product_id_product')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_order_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order')),
    sa.UniqueConstraint('order_code', name=op.f('uq_order_order_code'))
    )
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cs_ask', sa.String(length=50), nullable=False),
    sa.Column('cs_place', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('image_path', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modify_date', sa.DateTime(), nullable=True),
    sa.Column('answer_review', sa.Text(), nullable=True),
    sa.Column('answer_admin_id', sa.Integer(), nullable=True),
    sa.Column('answer_create_date', sa.DateTime(), nullable=True),
    sa.Column('answer_modify_date', sa.DateTime(), nullable=True),
    sa.Column('answer_status', sa.String(length=20), server_default='waiting', nullable=False),
    sa.ForeignKeyConstraint(['answer_admin_id'], ['user.id'], name=op.f('fk_review_answer_admin_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_review_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review'))
    )
    op.create_table('theater',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], name=op.f('fk_theater_region_id_region')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_theater')),
    sa.UniqueConstraint('name', name=op.f('uq_theater_name'))
    )
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('payment_key', sa.String(length=200), nullable=True),
    sa.Column('order_code', sa.String(length=100), nullable=True),
    sa.Column('method', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], name=op.f('fk_payment_order_id_order')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment')),
    sa.UniqueConstraint('payment_key', name=op.f('uq_payment_payment_key'))
    )
    op.create_table('screen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('theater_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('total_seats', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['theater_id'], ['theater.id'], name=op.f('fk_screen_theater_id_theater')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_screen'))
    )
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('screen_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.CheckConstraint('end_time > start_time', name='ck_schedule_time'),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], name=op.f('fk_schedule_movie_id_movie')),
    sa.ForeignKeyConstraint(['screen_id'], ['screen.id'], name=op.f('fk_schedule_screen_id_screen')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedule')),
    sa.UniqueConstraint('screen_id', 'start_time', name='uq_schedule_screen_start')
    )
    op.create_table('seat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('screen_id', sa.Integer(), nullable=False),
    sa.Column('row', sa.String(length=5), nullable=False),
    sa.Column('col', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['screen_id'], ['screen.id'], name=op.f('fk_seat_screen_id_screen')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seat'))
    )
    op.create_table('reservation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('seat_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='RESERVED', nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], name=op.f('fk_reservation_schedule_id_schedule')),
    sa.ForeignKeyConstraint(['seat_id'], ['seat.id'], name=op.f('fk_reservation_seat_id_seat')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_reservation_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reservation')),
    sa.UniqueConstraint('schedule_id', 'seat_id', name='uq_schedule_seat')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservation')
    op.drop_table('seat')
    op.drop_table('schedule')
    op.drop_table('screen')
    op.drop_table('payment')
    op.drop_table('theater')
    op.drop_table('review')
    op.drop_table('order')
    op.drop_table('answer')
    op.drop_table('user')
    op.drop_table('region')
    op.drop_table('product')
    op.drop_table('notice')
    op.drop_table('movie')
    op.drop_table('imgs')
    op.drop_table('faq')
    # ### end Alembic commands ###
